// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {preset} from '../models';

export function CreatePresetFile():Promise<string>;

export function CreateTorrent(arg1:main.CreateRequest):Promise<main.TorrentResult>;

export function DeletePreset(arg1:string):Promise<void>;

export function FormatBytes(arg1:number):Promise<string>;

export function GetAllPresets():Promise<main.PresetsResult>;

export function GetContentSize(arg1:string):Promise<number>;

export function GetPreset(arg1:string):Promise<preset.Options>;

export function GetPresetFilePath():Promise<string>;

export function GetRecommendedPieceSize(arg1:string,arg2:number):Promise<number>;

export function GetTrackerInfo(arg1:string):Promise<main.TrackerInfo>;

export function GetVersion():Promise<string>;

export function InspectTorrent(arg1:string):Promise<main.InspectResult>;

export function ListPresets():Promise<Array<string>>;

export function ModifyTorrent(arg1:main.ModifyRequest):Promise<main.ModifyResult>;

export function OpenURL(arg1:string):Promise<void>;

export function SavePreset(arg1:string,arg2:preset.Options):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectMultipleTorrentFiles():Promise<Array<string>>;

export function SelectPath():Promise<string>;

export function SelectTorrentFile():Promise<string>;

export function VerifyTorrent(arg1:main.VerifyRequest):Promise<main.VerifyResult>;
