// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePresetFile() {
  return window['go']['main']['App']['CreatePresetFile']();
}

export function CreateTorrent(arg1) {
  return window['go']['main']['App']['CreateTorrent'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function FormatBytes(arg1) {
  return window['go']['main']['App']['FormatBytes'](arg1);
}

export function GetAllPresets() {
  return window['go']['main']['App']['GetAllPresets']();
}

export function GetContentSize(arg1) {
  return window['go']['main']['App']['GetContentSize'](arg1);
}

export function GetPreset(arg1) {
  return window['go']['main']['App']['GetPreset'](arg1);
}

export function GetPresetFilePath() {
  return window['go']['main']['App']['GetPresetFilePath']();
}

export function GetRecommendedPieceSize(arg1, arg2) {
  return window['go']['main']['App']['GetRecommendedPieceSize'](arg1, arg2);
}

export function GetTrackerInfo(arg1) {
  return window['go']['main']['App']['GetTrackerInfo'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InspectTorrent(arg1) {
  return window['go']['main']['App']['InspectTorrent'](arg1);
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ModifyTorrent(arg1) {
  return window['go']['main']['App']['ModifyTorrent'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SavePreset(arg1, arg2) {
  return window['go']['main']['App']['SavePreset'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectMultipleTorrentFiles() {
  return window['go']['main']['App']['SelectMultipleTorrentFiles']();
}

export function SelectPath() {
  return window['go']['main']['App']['SelectPath']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}

export function VerifyTorrent(arg1) {
  return window['go']['main']['App']['VerifyTorrent'](arg1);
}
